#!/bin/csh

#
# Install
#
# Installs product "mrkcacheload" in the appropriate directory
#
# 1. cvs export -r mrkcacheload-#-#-# -d mrkcacheload-#-#-# mrkcacheload
# 2. ln -s mrkcacheload-#-#-# mrkcacheload
# 3. Copy Configuration.default Configuration
# 4. Edit Configuration
# 5. Install
#

cd `dirname $0` && source ./Configuration

if ( ! -d ${MRKCACHEDIR} ) then
	mkdir ${MRKCACHEDIR}
endif

if ( ! -d ${MRKCACHEINDIR} ) then
	mkdir ${MRKCACHEINDIR}
endif

if ( ! -d ${MRKCACHEBCPDIR} ) then
	mkdir ${MRKCACHEBCPDIR}
endif

if ( ! -d ${MRKCACHELOGDIR} ) then
	mkdir ${MRKCACHELOGDIR}
endif

#
# create symbolic links
#

ln -s mrkomim.py mrkomimByAllele.py
ln -s mrkomim.py mrkomimByMarker.py
ln -s mrkomim.py mrkomimByGenotype.py

