#!/bin/csh

#
# Install
#

cd `dirname $0` && source ./Configuration

if ( ! -d ${MRKCACHEDIR} ) then
	mkdir -p ${MRKCACHEDIR}
endif

if ( ! -d ${MRKCACHEINDIR} ) then
	mkdir -p ${MRKCACHEINDIR}
endif

if ( ! -d ${MRKCACHEBCPDIR} ) then
	mkdir -p ${MRKCACHEBCPDIR}
endif

if ( ! -d ${MRKCACHELOGDIR} ) then
	mkdir -p ${MRKCACHELOGDIR}
endif

